[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 40.6.0", "wheel"]

[tool.yapf]
based_on_style = "google"
column_limit = 88

[tool.isort]
profile = "google"
src_paths = ["opt"]
